### ISSUE TITLE
Make "Create community " button more conspicuous 

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#142]
**Is your feature request related to a problem? Please describe.**

Currently the "Create community " button gets a bit lost the universe of communities that an account may have. Also, the color of the button is similar to that of the buttons of members and transactions. 

**Describe the solution you'd like**
Include a drawing or illustration that clearly shows that the button is for creating a new community. Make button bigger and change colour. 

**Describe alternatives you've considered**
see above

**Additional context**
<img width="1181" alt="Screen Shot 2020-01-28 at 14 33 27" src="https://user-images.githubusercontent.com/57719975/73303205-9617b200-41db-11ea-9617-f08518a05999.png">

**Comment by zacck** [comment]
Hmmm @natillasol  I see and understand the issue you are facing, however, I am unsure about a bigger and perhaps more colorful Icon is what we need.

@heltonlr  what do you think about a floating action button for this? maybe it will conflict with the new mobile menu style perhaps we can put it on the navbar in mobile?

**Comment by heltonlr** [comment]
@natillasol  is right, this is not the standard color of our buttons, and in the desktop version it shouldn't have 100% width.

Let's do this way (The default for these pages is the button on the right and smaller/ 40px height):

![Screen Shot 2020-01-29 at 9 17 13 AM](https://user-images.githubusercontent.com/39558132/73356046-33282880-4278-11ea-85ac-78dbbe91c0d4.png)

**Governance example**
https://www.figma.com/file/xsJPUDZAvLTPPcEHxUjMmm/Governance-desk?node-id=4%3A445

In the future we need to discuss the existence of this button, since creating a community is not something simple

**Comment by zacck** [comment]
@heltonlr  was this in any of the designs? specifically for the `create community` button?

**Comment by heltonlr** [comment]
Sorry @zacck , i don't understand your question.

**Comment by lucca65** [comment]
@zacck we have no designs ready for the "Explore" tab, as far as I know.
