### ISSUE TITLE
New menu structure

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#242]
We currently have a small horizontal scroll on tiny screens (320px), so this new proposal will avoid this scroll because the menu has been optimized for 320px wide.

In desktop versions we can keep the menu text next to the icon, as we have space. In the mobile version, follow as shown in Figma.

There are 3 versions on Figma (language):

_English_
https://www.figma.com/file/ZFYjG821WJpUFXlxV4dfnO/Navigation?node-id=143%3A0

_Portuguese_
https://www.figma.com/file/ZFYjG821WJpUFXlxV4dfnO/Navigation?node-id=143%3A89

_Spanish_
https://www.figma.com/file/ZFYjG821WJpUFXlxV4dfnO/Navigation?node-id=143%3A148

**Comment by victorgdev** [comment]
Hey @heltonlr, with the changes from PR[309](https://github.com/cambiatus/frontend/pull/309) are we still changing the layout of the menu as requested in this issue.

Reason I am asking is because without the community tab there is no scroll-x behavior on mobile screen down to 320px of width. Please let me know.

**Comment by heltonlr** [comment]
I think that problem was solved in this case @victorgdev
