### ISSUE TITLE
Add emoji hash to transfers and payments page

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#257]
We need to use a emoji hash library to encode the transaction id. This information will be useful to be shown as a receipt of uniqueness to the transaction.

It will be only a frontend feature

Add it to:

- Payments history page
- View transfer page

**Comment by amiskov** [comment]
Here are some thoughts on it.

We can use `createdTx` field from the Transfer as a basis. Then we can shorten it somehow to 6 symbols and translate it to emoji with the library you [suggested earlier](https://github.com/cambiatus/frontend/issues/251#issuecomment-630400044).

For example:

- `createdTx` value `cee71e2cdd38a65f41bf4348ab2572beea232ab6d728baaaa097a21a3f69eb34`
- becomes `1IXDsV` (I used [this library](https://github.com/bibig/node-shorthash))
- and after `emoji.encode('1IXDsV').toString()` it becomes 🏠💖🍺📶🌗📵🅰📄.

We can tweak emojis as we like.

Some other thoughts:

- Is there any function in `sjcl` library to transform 64 symbols string to 6 symbols string?
- Maybe we can do it in Elm? Because ports for this task are not so pleasant to use.

**Comment by lucca65** [comment]
amazing, looks like we have a clear path ahead! Thanks @amiskov

**Comment by amiskov** [comment]
This issue is [implemented](https://github.com/cambiatus/frontend/pull/253/files#diff-467b3049ca57e1eeb2fc9ff0026b2678R484) as part of #253 PR for the Payment History page.

**Comment by lucca65** [comment]
closed by #253
