### ISSUE TITLE
Add option in a Features settings

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/frontend#299]
In Ticolones project we going to hide the following menu items

- Shop;
- Explore (may we hide this to Muda and other communities too);

More details, here:
https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Main-flow?node-id=948%3A689

**Important note:**
If the user disables Shop and Explore, the main menu must hide because it is weird only one item on the menu.

**Comment by lucca65** [comment]
@heltonlr hiding explore means what? That's confusing to me because the explore is a public page. So hiding it really does make sense to be a community setting? 

Maybe we can make the community hidden from the explore, this would make more sense

Can you share more details on why we are hiding it? Maybe we can just remove this screen entirely (its really not used by any of our communities -- which makes sense)

**Comment by heltonlr** [comment]
What do you think @muguika? Did You talk about to be visible only in app.cambiatus.io, correct?

Maybe we can remove it entirely as @lucca65 said end only shows it in app.cambiatus.io

🧐

**Comment by lucca65** [comment]
ok, just giving some feedback, on slack we discussed this issue and decided to remove the explore tab. Since the show already has a toggle we can safely close this issue

**Comment by heltonlr** [comment]
> ok, just giving some feedback, on slack we discussed this issue and decided to remove the explore tab. Since the shop already has a toggle we can safely close this issue

Right
