### ISSUE TITLE
Allow usage of Spanish as a mnemonic for private key generation

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#306]
**Is your feature request related to a problem? Please describe.**
A large part of our user speak Spanish. Sometimes that have trouble with English words

**Describe the solution you'd like**
To use BIP39 implementation of mnemonics to support the user language. We have examples here: https://iancoleman.io/bip39/#spanish

**Describe alternatives you've considered**
As far as I know there is no alternative

**Comment by lucca65** [comment]
We should implement this depending on the language selected

**Comment by amiskov** [comment]
@lucca65 I had a glance at it a bit, here's what I found out.

We already can access Spanis wordlist like this`bip39.wordlists.spanish`. It looks like we need to tweak the `mnemonic.generateRandom` function a bit to use it.

There's a caveat that needs some investigation. The generated PDF doesn't understand some Spanish letters:
![image](https://user-images.githubusercontent.com/140053/88798229-40818980-d1ad-11ea-8261-3fb8b2b66d52.png)

I guess we need to generate new `pdfMake.vfs` fonts with all the glyphs to display it work properly (not sure though).

So, we need to generate Spanish passphrase if the user has the Spanish language selected and otherwise generate the passphrase in English, right?

**Comment by lucca65** [comment]
> guess we need to generate new pdfMake.vfs fonts with all the glyphs to display it work properly (not sure though).

+1 That's exactly it. Probably the font we use don't have ç ñ and other characters

> So, we need to generate Spanish passphrase if the user has the Spanish language selected and otherwise generate the passphrase in English, right?

That's right. I would be good to have it a way that is easy to add other compatible languages, although catalan and portuguese aren't compatible

**Comment by amiskov** [comment]
Fine! @lucca65 I'll take this issue then?

**Comment by lucca65** [comment]
ok! Good luck bro!

**Comment by amiskov** [comment]
@heltonlr @lucca65 The issue with the missing glyphs from the Spanish alphabet could be solved by introducing a new font for the passphrase. I've chosen OpenSans since it's open-source and we can modify it for our purposes. I removed ligatures from it, so the #289 also will be solved. I think that's quite important because many users use their browsers to view PDFs.

Here's the change illustrated:
![image](https://user-images.githubusercontent.com/140053/89026482-751e4e00-d331-11ea-8c5a-b12d1bcae30b.png)

@heltonlr are you ok with changing the font for the passphrase this way?

**Comment by lucca65** [comment]
+1 on this. We had a user with a PDF containing this error last week, she was quite frustrated with it. Moving the text box to open sans will not change a lot and will save us trouble

**Comment by heltonlr** [comment]
Sure @amiskov , no problems for changing, and thanks for this.
