### ISSUE TITLE
Update Private Profile to display filled in KYC information 10

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#310]
Display new KYC information if the community the user has selected has enabled it. 

https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Main-flow?node-id=948%3A468

Update from the 3rd September, related to the Edit Profile page:

- All KYC data and the Name of the User _should not be editable_. We need to keep these fields disabled because they identify the user. User can fill Name and KYC fields only once: during the registration for new users, and during the invitation process to the KYC-enabled community [for the existing ones](https://github.com/cambiatus/frontend/issues/312).
- Users can’t edit KYC data, but they should be able to _remove KYC data_. Use [this design](https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Ticolones-version?node-id=948%3A468) for the Profile page.
- There is a probability for the users to make mistakes in their names or phone numbers. Also, existing users could have nicknames instead of their real names. Since we are making these fields disabled we should provide some way to contact us to ask for help correcting these kinds of mistakes.
---
- It’s ok to have Costa-Rican fields in the user Profile for now since we have KYC only for the users from Costa-Rica. We will improve it when we will actually need it.
- We have `is_verified` field. We could use it later if we need it. E.g. allow users to edit their KYC fields and the Name if the profile is not verified yet.

**Comment by amiskov** [comment]
If the current community (selected in the top-left dropdown) has KYC enabled, then the Profile page should have additional fields with the user's KYC information.
![image](https://user-images.githubusercontent.com/140053/91477902-b7429d00-e8a7-11ea-92dd-2a7511be53d8.png)

If the user doesn't fill all the KYC fields then he/she has read-only access to the community and can't sell/buy items, use objectives/actions, or transfer coins.

**Comment by lucca65** [comment]
@amiskov maybe we can leave the profile "out" of the scope of the selected community. My line of though is that the profile belongs to the user, not to the community. This is even shown in the UX, as the profile is accessible on the top menu, which has also the language (also not community dependent)

I think that its safe to keep the KYC info shown all times, but on exclusion show which communities he/she will loose access to

**Comment by lucca65** [comment]
any thoughts on this @heltonlr none of this is on the layouts

**Comment by heltonlr** [comment]
No problem lucca65 , I think. Let me know if you need some interface.

**Comment by amiskov** [comment]
I'm really happy that this time I started from the description of the task with my own words :) Thanks for your comments!

> leave the profile "out" of the scope of the selected community

Fair enough! User info belongs to the user, I agree! So, these fields are not community dependant, but country dependant. I mean how could we make sure that current MUDA users will not see "Cédula de identidad" in their profiles?

To avoid this we are using the invitation process. If the user is invited to the community with KYC-enabled, then he has these fields because he finished the invitation process and filled them. The same for existing users, who was re-invited to the community with KYC.

So, if the user (normal person, not company) has finished the invitation process for the KYC-enabled community, then he sees KYC fields in his profile. If he has not finished this invitation process, then he won't see these fields by default. I think in this case he could see this state of the UI (no KYC fields, but the button to switch them on after choosing the country):
![image](https://user-images.githubusercontent.com/140053/91583774-558f3b00-e95a-11ea-8101-b641f13cb76e.png)

@lucca65 @heltonlr am I missing something?

**Comment by heltonlr** [comment]
_"Fair enough! User info belongs to the user, I agree! So, these fields are not community dependant, but country dependant. I mean how could we make sure that current MUDA users will not see "Cédula de identidad" in their profiles?"_

Answer= I don't know if I understood correctly, but on the configuration page the admin defines which country KYC will be enabled for, selecting Costa Rica, Muda's members will not see KYC information.

**Config's page:**
https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Ticolones-version?node-id=1100%3A13

---

"To avoid this we are using the invitation process. If the user is invited to the community with KYC-enabled, then he has these fields because he finished the invitation process and filled them. The same for existing users, who was re-invited to the community with KYC.

So, if the user (normal person, not company) has finished the invitation process for the KYC-enabled community, then he sees KYC fields in his profile. If he has not finished this invitation process, then he won't see these fields by default. I think in this case he could see this state of the UI (no KYC fields, but the button to switch them on after choosing the country):"

Answer= But the user who was invited and did not complete the process should not be able to "enter" in the community, only after completing the entire registration with KYC information if it is enabled in the community. And when a user disables KYC, he would be logged out of the community and taken to the registration screen where he would need to fill in KYC information again to enter.

**But that was what I remember talking about at the beginning. Let me know if anything has changed about it.**

@amiskov and @lucca65

**Comment by lucca65** [comment]
@amiskov Yeah that brings problems, we can only have one type of KYC (which makes sense for most of users but no sense to nomads)

User has one KYC that has **one** KYC address witch in turn has **one** country. We cannot add two different KYC for the same user, at least for now (maybe we will support nomads in the future)

So the KYC can always be displayed at the profile, because it will not change depending on the community the user participates. But we will have the case of users trying to enter a community that uses -- lets say -- russian KYC, but the user already has a costa rican KYC. It should be blocked.

I think for now it will not be a problem since its not possible to have more than one country on the KYC. Every user that have KYC will be from costa rica, but it will bring problems eventually when we expand.

**Comment by lucca65** [comment]
@heltonlr about your comment:

> And when a user disables KYC, he would be logged out of the community and taken to the registration screen where he would need to fill in KYC information again to enter

It cannot work like that, you see, users may have multiple communities, we cannot log them out if they participate on more than one community. That's why we asked you to design a "locked" screen, that don't allow the user to do anything until he/she added the required KYC. The only things allowed is to accept invitations to other communities, use the community switcher and to fill in their KYC

Sometimes I think we didn't put enough though into the details of this implementation, as cases like these keep popping up as we work on the implementation.

**Comment by heltonlr** [comment]
In fact, we ran a lot to deliver this functionality and we extruded the solution little, even having an alignment meeting with the whole team.

So, let's continue with the interface that Andrew suggested, where the user must enable KYC to continue working in the community. I suggest, if possible, this modal if the user tries to do something that needs KYC

Figma
https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Ticolones-version?node-id=1497%3A16
(Please, consider only the modal)

**Comment by amiskov** [comment]
Thank you @heltonlr and @lucca65! I think I can continue the work on the Profile now and maybe will have more questions later!
