### ISSUE TITLE
Change invitation flow for existing users 15

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#312]
Users that are invited to a KYC enabled community must fill in more data when they are invited. The KYC is related to the user but we need to make sure we have everything during the community invitation process.

Related [Figma designs](https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Main-flow?node-id=3%3A2206) with all the fields the user should have filled in to join the community with KYC enabled.

**Comment by amiskov** [comment]
Here's how I see the flow:
![image](https://user-images.githubusercontent.com/140053/90560888-7e6c3f00-e1a8-11ea-9f68-eb542943e44b.png)

@lucca65 do I understand everything right?

How do you think, should we allow the existing users to accept invitations and become a company (show 2 additional screens with toggle, like during the registration)? It doesn't seem reasonable (existing users are not companies), but maybe I don't know all the details...

**Comment by lucca65** [comment]
>  It doesn't seem reasonable 

+1. The way I imagined, we would add the migration for the user type, defaulting every existing user to the `natural`  type. Then the invitation for existing users would just ask for the kyc information if needed, if not, it just adds to the community like normal

**Comment by amiskov** [comment]
Here's the invitation process flow for the existing user as I think of it:

![image](https://user-images.githubusercontent.com/140053/90630063-0560fc00-e229-11ea-83a2-f6119034355b.png)

**Comment by amiskov** [comment]
It looks like we need the backend part and the mutations for saving, updating, and deleting the KYC user data.

At first glance, it could be like this:

- create `saveKycData` mutation for saving the KYC data:
    + use it during the registration (#311 issue);
    + use it during the invitation of the existing user to the KYC-enabled community (this issue) for the user who hasn't KYC fields field;
- `updateKycData(account_id)` for updating user's KYC data from the profile page;
- `deleteKycData(account_id)` to delete the user's KYC info if he/she wants to do so.

Here are my concerns about that:

- we already have `updateProfile` mutation and it looks reasonable to use it also for updating the KYC fields from the Profile page. I see it like this: send all the user profile fields (including KYC) with `updateProfile` mutation and handle the data update on the backend (update KYC parts in the `kyc_table`, save user data to the `users` table).
- we already have `signUp` mutation and it is also reasonable to send all the data from Register/Invite page to it and handle saving to different tables on the backend.

So, here's my proposal:

- Don't create mutation specifically for the KYC data, use already existing `signUp` and `updateProfile` and handle saving/updating KYC info on the backend. From the API user's perspective, it looks pretty straightforward.
- Add `deleteKycData` mutation for deleting KYC, because we have the law that the user must have this ability.

What do you think about this @lucca65 @RodrigoLeiteF?

**Comment by lucca65** [comment]
We will need to do two mutations on this. Since signup is a non-atomic operation, we will need to make sure the account creation/netlink process finishes before submitting the KYC data. Even if in the screen the process is the same
