### ISSUE TITLE
Make the app know if the user don't have KYC filled in 15

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#313]
In communities that have KYC enabled we need to find a way to block users actions if their profile is not filled in yet.

This can happen to existing users that removed their KYC information due to privacy reasons

**Comment by amiskov** [comment]
@heltonlr @lucca65 Please, check my thoughts on this task and let me know if I missed something or if you have your own thoughts!

The solution is to show the locking screen to the user with empty KYC info when he/she is trying to access the community with KYC enabled. We have [this design](https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Ticolones-version?node-id=1497%3A16) for the locking overlay, but my suggestion is to _show the whole page_, similar to the "Not found". Something like this:

![image](https://user-images.githubusercontent.com/140053/92127324-dbebc700-ee09-11ea-8a53-7d1b36030dba.png)

I suggest this because I think that we should _check if the user has access to the community on the backend and send no data if access is restricted_. Otherwise, it's pretty simple to do things on the frontend with the developer console and with the GraphQl queries. I guess we can add this validation as a middleware (Plug or something like that) on the Phoenix side.

Also, I think that we should always allow the user to access the Profile and the Profile Edit page so he/she can add the KYC info to get access.

Here is my understanding of the flow when this screen could be shown:

![image](https://user-images.githubusercontent.com/140053/92124773-e062b080-ee06-11ea-9ad1-43dabd4738fc.png)

The same checking should be applied for the logging-in process and for the deleting the KYC info by the user when he/she has some KYC-enabled community selected as current.

**Comment by heltonlr** [comment]
I would like to add a button on this screen to enable KYC and the user can fill in the data.  It's possible?

@amiskov andrew

**Comment by amiskov** [comment]
> I would like to add a button on this screen to enable KYC and the user can fill in the data. It is possible?
Yes, sure! It will be pretty convenient.

**Comment by heltonlr** [comment]
Awesome, button label: "Fill data"

Then, redirect to the form.
