### ISSUE TITLE
Refactor sending the invitation ID in while register

### ISSUE THREAD

**Issue by amiskov** [cambiatus/frontend#372]
**Is your feature request related to a problem? Please describe.**
This is not a problem, but code clarification for the future us. The types for Natural/Juridical forms with invitation ID could be more restrictive/straightforward.

**Describe the solution you'd like**
Figure out the types for the forms with/without invitation ID, see #370.

**Comment by lucca65** [comment]
@amiskov Since you are working on this can you squeeze in another fix? We only send the signup after creating the key and displaying the 12 words. It may happen that the backend fails, we don't do nothing in that case. We should send the sign up to the backend and only after it succeeds we should show the 12 words to download.

One way to simulate this is to accept an invitation for a KYC enabled community and use this query:

```json
{"query":"mutation {\n  signUp3654761766: signUp(input: {account: \"1qwerqwerqwe\", email: \"test@user.com\", invitationId: \"7wmLW4\", name: \"A\", publicKey: \"EOS4wVU7pVkNxiFbv4BTpsGDvtxsBXfKVN8e296zyz93DgjH5xof5\"}) {\n    status955176064: status\n    reason3832528868: reason\n  }\n}"}
{"query":"mutation {\n  upsertKyc410207898: upsertKyc(input: {accountId: \"1qwerqwerqwe\", countryId: \"1\", document: \"12345678\", documentType: \"cedula_de_identidad\", phone: \"11111111\", userType: \"natural\"}) {\n    __typename\n  }\n}"}
```

this data fails because of the `cedulad_de_identidade` is invalid, but the user never gets the change to correct it.

We should support signup with KYC details instead of doing two calls to be honest...
