### ISSUE TITLE
Update Creating and Editing Action forms to allow for the new photo proof  5

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#391]
- [x] Add spans for odd numbers of verifications
- [x] New radio for enabling the photo proof
- [x] New radio for enabling the proof number
- [x] New input for adding proof instructions
- [x] Make the form send/receive data for the fields above from the backend.

**Comment by amiskov** [comment]
@lucca65, can you please check if I have the right understanding of the create/update Actions mechanics. Here's how I see it, please, correct me if I'm wrong!

On the frontend, new fields for `has_proof_photo`, `has_proof_code`, and `photo_proof_instructions` should be added to `data` field here: https://github.com/cambiatus/frontend/blob/b230fc7f364250eb0b7b10387c28ac0f1eb53b51/src/elm/Page/Community/ActionEditor.elm#L1039-L1060

There's no GraphQl mutation for creating/updating Action because the Action should be created/updated via blockchain: the data will be sent to the blockchain via js-port first and then it will be added to the Postgres DB via event-source.

**Comment by lucca65** [comment]
That is correct @amiskov !
