### ISSUE TITLE
Only one (the first) verifier can vote the claim

### ISSUE THREAD

**Issue by amiskov** [cambiatus/frontend#409]
**Describe the bug**
I tested Claims on Staging trying to follow all steps for creating, verifying and receiving coins. It looks like we have some things to be fixed.

**To Reproduce**
Here are several users (claimer and verifiers) and their claiming/voting process:
- ✅ `andreystagin` creates a Claim for action "Read SICP for an hour" from "Become a better programmer" objective.
- The validators/verifiers for this action are:
    - `andreymiskov`
    - `amiskovstag4`
    - and `amiskov12341`
- ✅ Validators have Claim in their Dashboard and Analysis pages.
- Check if all validators can vote from the Dashboard.
    - ✅ `amiskov12341` votes:
        - ✅ Voting UI was fine.
        - ✅ Verified claim was removed from the Dashboard and available on the Analysis page without voting buttons.
    - 🐛 Then `amiskovstag4` votes:
        - 🐛 He realizes that the Claim card disappeared from the Analytics page. This happened after the first vote by `amiskov12341`. The Claim is only available on the Dashboard.
        - 🐛 After trying to approve the Claim from the Dashboard he got 500 error from the server and "failed" word on the UI in place of a Claim card:
        ![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2Famiskov%2FsWhwHz2jSF.png?alt=media&token=11ecec03-0dee-45fa-bd79-1d9812c787b9)
        `"{"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[{"message":"assertion failure with message: The verifier cannot check the same claim more than once","file":"wasm_interface.cpp","line_number":1075,"method":"eosio_assert"},{"message":"pending console output: ","file":"apply_context.cpp","line_number":113,"method":"exec_one"}]}}"`
    - 🐛`andreymiskov` votes:
        - All the same as for `amiskovstag4`

**Expected behavior**
- Pending claim card is avalable for all verifiers on the Dashboard and Analytics page.
- Claim card approved or disapproved by verifier disappears from the Dashboard but still available on the Analytics page without voting buttons.
- All verifiers are available to vote on the pending claim.

**Cambiatus Env you are using**
Tried on my localhost and on Staging. The behavior is the same.

**Additional context**
Maybe I'm not fully understand the logic of the claim verification. @lucca65 I will much appreciate your help/clarification with this!

**Comment by lucca65** [comment]
@amiskov First, thanks for the extensive testing, this is indeed a feature that takes effort to test. 

Basically we have two problems: **Listing claims** and **Processing votes**

### Listing claims

> 🐛 He realizes that the Claim card disappeared from the Analytics page. This happened after the first vote by amiskov12341. The Claim is only available on the Dashboard.

So this is, for certain a bug that came from backend. We have two queries that respond to the related pages. Although they are very similar, they also have different implementations. Their implementation was done through several iterations of trial and error, with different refactors and changing screens. Never got the chance to properly test them, though. 

First we have the function [`claim_analysis_query/2`](https://github.com/cambiatus/backend/blob/ffc3066a770588da4fcc1295716e715d0a7cb479/lib/cambiatus/commune/commune.ex#L222)
This query is used on the frontend's dashboard. It must show only pending claims that the logged user haven't voted yet. This is why we have a `WHERE/JOIN` that counts the votes:

```elixir
|> where(
      [c, a, o, v],
      o.community_id == ^community_id and v.validator_id == ^account and a.is_completed == false and
        c.status == "pending" and
        fragment(
          "select count(*) from checks b where b.claim_id = ?.id and b.validator_id = ?",
          c,
          ^account
        ) == 0
    )
```

and then we have the [`claim_analysis_history_query`](https://github.com/cambiatus/backend/blob/ffc3066a770588da4fcc1295716e715d0a7cb479/lib/cambiatus/commune/commune.ex#L249)

This other one is less picky. The only thing that it cares is for claims where the logged user is a validator. I feel if there is a problem on this query, it could be on the types of joins and this particular `WHERE` clause: 

```elixir
      where: fragment("?.validator_id = ? OR ?.claim_id IS NULL", ch, ^account, ch),
```

### Processing votes


Processing votes is tricky, mainly because it envolves automatically updating statuses of claims as the votes come along. We do a lot of counting and checks to make sure the vote is valid. After the voting is inserted, we have to update the claim, and depending on the status of the claim, we need to update the action.

Lets explain in a little more detail this part...

- **Actions**: Actions are a very flexible structure that allows for multiple scenarios of usage. Maybe the most basic one is allowing for the ~Validity~ of an action. This can be by _date_ and _quantity_
  - _Date_: its pretty straightforward. The action can be claimed until a certain date. After that date is met, its no longer possible to open new claims. An important part is that the claims themselves can be validated after this date is met. Only new claims that cannot be created.
  - _Quantity_ : Maybe we should have called this _usages_, but it determines the number of times this action can be **Approved or Disapproved**. That means that the users can claim all they want, but only the specified number can lead to rewards. So lets say we configure this action to have `Quantity of 3`; we can have 100s of claims opened, but after the 3 one is voted fully (approved or disapproved) the rest will be "unvoteable:, as the action will change its status to "completed" (that is set the flag `is_completed` to `true`.
  - _Verification_: Aside of the flexibility allowed by the previous two fields, we also provide two ways of a claim to be made. _Automatic_ and _Manual_
    - _Automatic_: This validation requires nothing more than a contract call, it will reward the users directly as specified in the [`verifyaction`](https://github.com/cambiatus/contracts/blob/master/community/community.hpp#L202) function. This function requires an `maker` param which will be the user rewarded. Those actions were created aiming for automation from the communities to give rewards based of a process that is automatically verified. For example, on the [Entre Pulperias](https://www.facebook.com/entrepulperoscostarica/) app, the users earn tokens by doing e-learning classes. Since the software can tell if they actually did the class, the rewarding can be made without human interaction
    - _Manual_: As the name implies, it requires manual verification before rewarding. Basically it means that we need human verification and interaction in order to reward the users for doing an action for their community. It allows us to configure a number of verifications and require us to have an odd numbers of validators. I think its not the best context to explain in more depth about those rules, but we do have to find a way to settle the voting, and we use [Supermajority](https://en.wikipedia.org/wiki/Supermajority#Majority_of_the_entire_membership) voting system.

That explains a little more about actions. The general flow for **manual verification** actions is:

Create action -> Claim action -> Voting -> Rewarding

We do have a part of our contract that updates the status of the claim as the voting comes to its required number of votes. It also updates the status of the action, updating usages and checking if the action has come to a moment where it should be completed or not, depending on the configured rules. 

All of that can be checked on our longest contract action [`verifyclaim`](https://github.com/cambiatus/contracts/blob/master/community/community.cpp#L471-L706). The specific line that throws the error mentioned is [this one](https://github.com/cambiatus/contracts/blob/master/community/community.cpp#L613). [I've recently changed it after an epiphany during a meeting with the design team](https://github.com/cambiatus/contracts/pull/22), maybe this can be fixed by a simple deploy on the staging contract. 

Either way we need a full investigation here. Using [bloks to analyse the tables](https://local.bloks.io/account/cambiatus.cm?nodeUrl=staging.cambiatus.io&coreSymbol=SYS&systemDomain=eosio&loadContract=true&tab=Tables&account=cambiatus.cm&scope=cambiatus.cm&limit=100&table=check) can be a good debugging tool 

> And a little detour on the explanation, we have also to implement this same interaction with objectives at some point, as today, you don't have a way to set an objective as completed.

**Comment by amiskov** [comment]
Fixes for this issues was added on [the contract](https://github.com/cambiatus/contracts/pull/22) and on [the backend](https://github.com/cambiatus/backend/pull/103).
