### ISSUE TITLE
Fix inconsistent state on app load

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#424]
<img width="516" alt="Captura de Tela 2020-11-06 às 19 35 57" src="https://user-images.githubusercontent.com/1082127/98757737-e8f9d900-23ab-11eb-940f-3bb24946ba55.png">

Not sure if its noticeable right away, but the token and the community don’t match. The community selector is also not available. Normal operations fail mysteriously.

instructions on how to replicate the bug:
First you have to get an invitation from any community other than Cambiatus. Just generate a new link, lets say for MIZU and logout.
Now open the invitation and register a new user. It should work as expected. Now reload the page. All is messy, no community selector, welcome message pointing to cambiatus, but your dear tokens, on the right place

**Comment by amiskov** [comment]
@lucca65 Maybe this is not so serious as we thought!

> The community selector is also not available

That's because the new member has only one community. There's nothing to choose from the selector.

This happens because we don't save the current community to the `localStorage` after registration and logging in. This may be fixed pretty easily, here's [the PR](https://github.com/cambiatus/frontend/pull/452).
