### ISSUE TITLE
Implement multi domain support

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#495]
Implement multi domain support

- Add screens to configure a subdomain
- Auto redirect the user when changing communities 
- Share local storage with all domains

**Comment by lucca65** [comment]
Some considerations we need to keep in mind:

- What we should do when we found a non existing URL. On both logged in (show community selector only) and guest (deny the request completely)
- Show community selector on app.cambiatus.io, or when the user tries to enter a community that the user don't belong to and that don't allow for auto invites
- Auto invites: allow communities to choose if they allow auto-invite (sign up without invitation_id)
- capacity to understand that we are on demo/staging/other 
- when the backend receives an `SignUp` without `invitationId`, it should look for the origin to determine if its possible to SignUp

**Comment by NeoVier** [comment]
Just to keep track of things, here's a TODO list:

- [x] Load appropriate community based on URL
- [x] Store all community data only on `LoggedIn`
- [x] Remove symbols (like `0,CMB`) from URLs
- [x] Add new community configuration pages
  - [x] General information (name, description, subdomain, etc)
  - [x] Currency (inviter reward, invited reward, minimum balance)
- [x] Auto redirect the user when changing communities
- [x] Share local storage with all domains

All of the above are from #494 

- [ ] Adapt sign in process to know if the community allows users to join without being invited
- [ ] Fix it so we use the community's custom subdomain instead of just the community name
- [ ] Change what happens when the user enters app.cambiatus.io or an invalid subdomain
  - [ ] Logged in: show community selector (#482)
  - [ ] Guest: redirect to cambiatus.com
- [ ] Change plausible tag (#513)

**Comment by lucca65** [comment]
Hey @NeoVier I've started working on the domain support on the backend. Check here: https://github.com/cambiatus/backend/pull/149
