### ISSUE TITLE
Show number of votes on claims

### ISSUE THREAD

**Issue by NeoVier** [cambiatus/frontend#559]
**Is your feature request related to a problem? Please describe.**
In order to know how many people have voted on a claim, people have to click on the claim, open the claim page, and see who has already voted

**Describe the solution you'd like**
Show the number of votes on the claim card and on the claim page

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by NeoVier** [comment]
@rafachadud @juramos-2020 do we have a design for this already?

**Comment by juramos-2020** [comment]
Hi @NeoVier @lucca65 @rafachadud 

Now that we have the claim opening a modal, is it still necessary to have this information on the number of votes on the card?

https://www.figma.com/file/LTaoCg6DKv6EPQAlt6Fngs/New-analysis-page?node-id=64%3A1413

As you can see on this screen, when you open the modal, the number of people who voted for the claim appears

**Comment by lucca65** [comment]
I still think this is needed, because a validator has no way to know if this action requires 3,5, 7 votes. 

also since "no one" looks like an user, it can be misleading 

>As you can see on this screen, when you open the modal, the number of people who voted for the claim appears
It shows who voted on what but not the number done and the number required

**Comment by juramos-2020** [comment]
In this case, the number done and the number required should they appear on the card or when opening the modal?

**Comment by lucca65** [comment]
I think the numbers could appear on the modal, but on the cards we could have a progress bar, this way validators can quickly inspect the ones needing more attention, without having to open them up or read anything.

here is a quick video with several cards with progress bars on it: https://www.youtube.com/watch?v=juLk17Awr_Q

**Comment by NeoVier** [comment]
I think it would be nice to have a progress bar like the one from GitHub:
![2021-06-08-154357_129x31_scrot](https://user-images.githubusercontent.com/39280468/121240123-64533880-c870-11eb-8d03-78513e5503cd.png)
Where it shows the number of people that voted yes, the number of people that voted no and the number of people that still have to vote

**Comment by lucca65** [comment]
+1! I like the idea of having a notion on how its going just by glancing at it!

**Comment by juramos-2020** [comment]
that's right. I also think it makes more sense if this information appears on the card.

we already have something similar on the governance screen. I can do something like this:

https://www.figma.com/file/7Ci3rdDNQQ7KabYyDLE3LY/Governance?node-id=4%3A445

**Comment by lucca65** [comment]
I like it @juramos-2020, it could be a little different as we have approvals/reprovals and then missing votes, which could be gray or something like it!

Also we can have a different way to showing it when voting is completed

because lets imagine it requires 5 votes. 

3 positives and 2 negatives are complete
3 positives and 2 pending is also complete
3 negatives and 2 positive too.. and so on

completion means you don't have to do anything else, but might not "fill the bar" you know?

**Comment by juramos-2020** [comment]
Yes, I know. 

I can create a proposal until friday. Can be?
@lucca65 @NeoVier

**Comment by lucca65** [comment]
I love the bars! the colors are bright and visible! Do you think we could bring the status tag (approved, disapproved, pending) more close to the progress bar?

**Comment by NeoVier** [comment]
I love it @juramos-2020, good job! :fire:

**Comment by juramos-2020** [comment]
Hi @lucca65 

I made an example to show you what it would like with the tag next to the progress bar. The impression it gives me is that have two elements talking the same thing. 

https://www.figma.com/file/LTaoCg6DKv6EPQAlt6Fngs/New-analysis-page?node-id=265%3A312

I was think about this... What if on this screen (which shows the already analyzed claim) we used only one of these elements?
We could just use the tag. 

Even because the progress bar arose from the need for administrators to quickly analyze those claims that still needed votes.
So I think it makes sense for it to be only in the "claims that need to vote" screen. 
In the "claim analyzed" screen have only the tag and when clicking "more details" the admin will have the details of the votes.

What do you thing?

**Comment by NeoVier** [comment]
@juramos-2020 Not sure how I feel about not showing the bars on the "Analyzed" page... some people might still want to see how the voting is going, or just know the result from a glance. Maybe we could incorporate the function of the tag on the bar itself and get rid of the tag? What do you think @juramos-2020 @lucca65?

**Comment by lucca65** [comment]
i love this solution, because the way the tag is, it's not as visible as it could be...

**Comment by juramos-2020** [comment]
Hi @lucca65 and @NeoVier 

Here is of the new scren:  

https://www.figma.com/file/LTaoCg6DKv6EPQAlt6Fngs/New-analysis-page?node-id=230%3A143

**Comment by victorgdev** [comment]
@lucca65 and @NeoVier can I tackle this issue?

**Comment by NeoVier** [comment]
@victorgdev go ahead bro! This one should actually be a good first issue :sweat_smile:

You've already seen the part of the code that deals with claims, so you kind of know where to find information on approved/disapproved/pending votes each claim has (and we already have all that information on the frontend), so this one should be :cake:

**Comment by lucca65** [comment]
+1000
