### ISSUE TITLE
Weird image display on the shop 

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#655]
**Describe the bug**
Some images don't load on the shop listing, or don't show anything although the product does have images

**To Reproduce**
1. Go to Muda's Shop (https://muda.cambiatus.io)
2. ctrl+F your way with the word "comp"
3. See error

Some cases on the shop don't display images correctly, like:
- https://muda.cambiatus.io/shop/1034
- https://muda.cambiatus.io/shop/1042

But this only happens on the listing, the details view seems ok!

**Expected behavior**
If the product has no images, it should show the place holder

**Screenshots**

- Placeholder displaying correctly:
  - <img width="364" alt="Captura de Tela 2021-11-01 às 15 41 32" src="https://user-images.githubusercontent.com/1082127/139723788-b962e284-b5de-4166-8f53-22bf633f6f9b.png">
- No image, but no placeholder:
  - <img width="367" alt="Captura de Tela 2021-11-01 às 15 42 51" src="https://user-images.githubusercontent.com/1082127/139723953-72e77e0a-aae2-4c01-bf01-f57aaae3e800.png">

**Cambiatus Env you are using**
https://muda.cambiatus.io/shop and https://muda.cambiatus.io/shop/1174. The detail appear correctly, but on the listing, no

**Desktop (please complete the following information):**
Safari

**Smartphone (please complete the following information):**
N/A

**Additional context**
Found by @flpfar

**Comment by NeoVier** [comment]
@lucca65 seems like the problem is when we create an offer. If the user hasn't supplied an image, we send an empty string instead of a url (from what I've tested, if we send `null` or don't include the `image` field, the eos transaction fails - the image field is a required string). And then when we fetch the offer (using graphql), we get `Just ""` on the image field.

A simple solution is just to detect the empty string on the selection set itself, and set the product's image to `Nothing` if it's equal to `Just ""`. It's not the best solution, but it's quick and easy, especially since we're going to revamp the shop soon anyway.

Or we could treat it on the contract level, or maybe even on the backend. Where do you think we should handle this?

**Comment by lucca65** [comment]
On the contract I think the max we can do now is start requiring that the string contains a certain length. As far as I know we cannot have optional or null values on the contract. For the event-source ingestion I think it is quite easy to check for "" and save it as NULL, since our database does support it. I'll send a quick fix for it in the coming minutes.

**Comment by lucca65** [comment]
change on event-source ✅

**Comment by NeoVier** [comment]
Since that doesn't deal with offers that have already been created, I've opened #656 , which also addresses some minor stuff we talked about during our meeting!

**Comment by lucca65** [comment]
sweet!
