### ISSUE TITLE
Depending on the selected language, the menu profile icons get small

### ISSUE THREAD

**Issue by lucca65** [cambiatus/frontend#659]
**Describe the bug**
Depending on the selected language the profile menu icons get really tiny, to a point that they look like a small square

**To Reproduce**
1. Open any logged page
2. Change to portuguese or English
3. See error

**Expected behavior**
The icons should be the same size regardless of the text

**Screenshots**

<img width="132" alt="Captura de Tela 2021-11-12 às 13 27 36" src="https://user-images.githubusercontent.com/1082127/141514814-3861a1ff-1152-4050-ad49-38cd51667dcd.png">
<img width="158" alt="Captura de Tela 2021-11-12 às 15 12 33" src="https://user-images.githubusercontent.com/1082127/141514854-3fb03295-1c2f-48bb-9784-06a0600a20df.png">

**Cambiatus Env you are using**
Happens on all envs (dev, demo and staging), **but use `karla` or `lucca` account. Its related to the account name length

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
Doesn't happen on mobile

**Additional context**
N/A

**Comment by NeoVier** [comment]
Since we're messing with it on this issue, I just realized another issue related to the profile name which happens on desktop when the search bar is open:

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/39280468/153665359-485f8670-29a1-4386-b0ba-9bca3214f242.png">

It shouldn't wrap the line, it should look like this:

<img width="228" alt="image" src="https://user-images.githubusercontent.com/39280468/153665431-5e5276ab-a658-4a3d-85b4-b4de46b52f4c.png">
