### ISSUE TITLE
Verifiers cannot verify themselves

### ISSUE THREAD

**Issue by natillasol** [cambiatus/frontend#79]
**Is your feature request related to a problem? Please describe.**

During the meeting with Borboins the users asked if it was possible to avoid verifiers verifying themselves, in order to avoid inadequate use of the tool .

**Describe the solution you'd like**
Not allow verifiers to verify themselves 

**Describe alternatives you've considered**

**Additional context**

**Comment by lucca65** [comment]
Maybe we can include @muguika into this conversation. AFAIK the verifier is a trusted user in the community. We surely can add this feature, but I just want to make sure we **really** want this. Usually trust issues are more related to human to human interactions. Maybe a verifier that isn't honest shouldn't be a verifier at all. 

Maybe we can have a screen that shows the "work" of verifiers to allow the community to know how they are doing, instead of simply removing an ability that might be useful in some cases (where, for example, there is a small community with only one verifier that does it all)

**Comment by muguika** [comment]
I understand what they were asking for, more than an issue of trust it really doesn't make much sense to verify oneself... is like having users that can claim actions directly. I was thinking on the similar example of la COOP, in which August will be the only verifier of an action:  attending an event (that he hosts). If he is the host and only verifier, it seems about right that he won't claim that action himself, and if he wants to do that, then he should add another verifier than will be able to verify him.

I like this @lucca65  "Maybe we can have a screen that shows the "work" of verifiers to allow the community to know how they are doing" 

But I'm not sure about this "an ability that might be useful in some cases (where, for example, there is a small community with only one verifier that does it all)"...  should we encourage that type of centralization in one user? even in our current more closed pilots?

**Comment by lucca65** [comment]
@muguika, yeah i’m throwing ideas to see how the go.

The panel that shows some kind of report of the most active users and the activity verifiers should be enough to make those

**Comment by heltonlr** [comment]
I suggest do not allow only one verifier, at least 2. Thus, if a verifier claims his own activity, the vote of the second verifier will be decisive. In such cases a single vote will be required.

We can group some ideas, choose the most interesting and take for evaluation in the pilots, what do you think?

**Comment by lucca65** [comment]
@natillasol @heltonlr I'll close this issue as a new consensus has been reached, and with that another task
